#!/usr/bin/env python

import os
import sys

import torch
from diffusers import StableDiffusionPipeline

MODEL_CACHE = "diffusers-cache"
os.makedirs(MODEL_CACHE, exist_ok=True)


pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    cache_dir=MODEL_CACHE,
    use_auth_token=sys.argv[1],
)
